import type { Metadata } from "next";
import Link from "next/link";
import CallsDiagnostic from "@/components/CallsDiagnostic";
export const metadata:Metadata={title:"HVAC Calls Slowing Down? Compare What Changed | Sequoia GEO",description:"Separate traffic changes from call-answering and booking changes with a transparent diagnostic for home-service owners.",alternates:{canonical:'/resources/where-are-my-calls-going'}};
export default function Page(){return <article className="max-w-4xl mx-auto px-5 pt-28 pb-24">
  <Link href="/resources" className="inline-block underline mt-4">Owner decision resources</Link>
  <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mt-8">Your calls slowed down.<br/>What actually changed?</h1>
  <p className="text-xl leading-relaxed mt-6">Before replacing your agency or increasing your ad budget, separate three questions: Are fewer people finding you? Are fewer prospects calling? Are fewer of those calls becoming appointments?</p>
  <p className="mt-5 text-gray-700">For HVAC, plumbing and other home-service owners. Compare observed counts, identify the next report to inspect, and bring a better question to your marketing meeting.</p>
  <a href="#diagnostic" className="btn btn-dark mt-6">Compare my numbers</a>
  <section className="mt-12"><h2 className="text-2xl font-bold">Is it seasonality or your agency?</h2><p className="mt-4 leading-relaxed">A drop in calls alone cannot answer that. Compare the same services and sources over complete periods, then inspect demand, visibility, tracking, website actions and call handling separately. Seasonal comparisons also need local weather, comparable prior-year periods and service mix. This tool does not retrieve those reports or diagnose causation.</p></section>
  <CallsDiagnostic/>
  <section className="space-y-5"><h2 className="text-2xl font-bold">Read the pattern before choosing the fix</h2>
    <h3 className="font-bold text-lg">Traffic fell, but call handling held up</h3><p>Inspect Search Console by query and page, and GA4 by source and landing page. Check whether tracking, paid budgets, hours or service areas changed. Your website impressions are not a measurement of the entire market.</p>
    <h3 className="font-bold text-lg">Calls held up, but fewer were answered</h3><p>Review missed calls, time of day, staffing and callback outcomes. In the illustrative example, 50 eligible calls arrive in each period, but answered calls fall from 45 to 30. The answer rate falls from 90% to 60%, while the booking rate among answered calls stays at 60%. That points to call handling as a place to investigate, not proof that marketing is healthy.</p>
    <h3 className="font-bold text-lg">Answering held up, but bookings fell</h3><p>Listen to appropriately authorized recordings and review dispositions. Appointment availability, job fit, geographic coverage and customer objections can affect booking. Do not assume the CSR or agency caused the decline.</p>
    <h3 className="font-bold text-lg">What if you do not have the numbers?</h3><p>Leave them blank. Ask for source-level call logs, booking outcomes and consistent reporting dates. Do not substitute phone-button clicks for actual calls or calendar clicks for completed bookings.</p>
  </section>
  <section className="border-t mt-10 pt-8"><h2 className="text-2xl font-bold">How the calculation works</h2><p className="mt-4">Count change is later minus earlier. Percentage change is that difference divided by the earlier count. A zero earlier count has no defined percentage change. Answer rate is answered eligible calls divided by eligible calls. Booking rate is bookings divided by those answered calls. Rates require matched call sets and positive denominators.</p><p className="mt-4">There is no proprietary score, industry benchmark or statistical significance claim. Source-level visits and calls are not joined, so the tool does not calculate a website conversion rate. Appointment bookings are not completed jobs.</p></section>
  <section className="mt-10 bg-[#eef3ed] p-6 rounded-xl"><h2 className="text-2xl font-bold">Bring the reports, not just the dashboard score</h2><p className="mt-3">Book a 15-minute call to discuss what changed and what evidence to collect next. Your entries are not automatically sent with the booking.</p><Link href="/contact#book" className="btn btn-dark mt-5">Book a 15-Minute Call</Link></section>
  <p className="mt-8">Related: <Link className="underline" href="/fractional-cmo">Marketing leadership</Link> · <Link className="underline" href="/leaving-my-marketing-agency">Agency transitions</Link> · <Link className="underline" href="/ai-search-methodology">AI-search measurement</Link></p>
</article>}
